// Code generated by protoc-gen-codec-go. DO NOT EDIT.
// source: lang/go/integration/cross.proto

package integration

import (
	fmt "fmt"
	codec "go.stealthscale.io/protoc-gen-codec/lang/go/codec"
	external "go.stealthscale.io/protoc-gen-codec/lang/go/integration/external"
)

func (m *CrossContainer) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.Name) > 0 {
		l := len(m.Name)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	if m.Item != nil {
		if sz := m.Item.SizeCodec(); sz > 0 {
			n += 1 + codec.SizeVarint(uint64(sz)) + sz
		}
	}
	for idx := range m.Items {
		elem := &m.Items[idx]
		sz := elem.SizeCodec()
		n += 1 + codec.SizeVarint(uint64(sz)) + sz
	}
	for _, elem := range m.PtrItems {
		if elem == nil {
			continue
		}
		sz := elem.SizeCodec()
		n += 1 + codec.SizeVarint(uint64(sz)) + sz
	}
	return n
}

func (m *CrossContainer) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n := m.MarshalCodecInternal(buf)
	return buf[:n], nil
}

func (m *CrossContainer) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeCodec() {
		return 0, codec.ErrBufferTooShort
	}
	return m.MarshalCodecInternal(buf), nil
}

func (m *CrossContainer) MarshalCodecInternal(buf []byte) int {
	n := 0
	if len(m.Name) > 0 {
		buf[n+0] = 0x0a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.Name)))
		n += copy(buf[n:], m.Name)
	}
	if m.Item != nil {
		if sz := m.Item.SizeCodec(); sz > 0 {
			buf[n+0] = 0x12
			n += 1
			n += codec.EncodeVarint(buf[n:], uint64(sz))
			n += m.Item.MarshalCodecInternal(buf[n:])
		}
	}
	for idx := range m.Items {
		elem := &m.Items[idx]
		buf[n+0] = 0x1a
		n += 1
		sz := elem.SizeCodec()
		n += codec.EncodeVarint(buf[n:], uint64(sz))
		n += elem.MarshalCodecInternal(buf[n:])
	}
	for _, elem := range m.PtrItems {
		if elem == nil {
			continue
		}
		buf[n+0] = 0x22
		n += 1
		sz := elem.SizeCodec()
		n += codec.EncodeVarint(buf[n:], uint64(sz))
		n += elem.MarshalCodecInternal(buf[n:])
	}
	return n
}

func (m *CrossContainer) UnmarshalCodec(data []byte) error {
	return m.UnmarshalCodecInternal(data, string(data), 0)
}

func (m *CrossContainer) UnmarshalCodecInternal(data []byte, slab string, slabOff int) error {
	_ = slab
	_ = slabOff
	l := len(data)
	i := 0
	var seenOptional uint64
	m.Name = ""
	for idx := range m.Items {
		(&m.Items[idx]).ResetCodec()
	}
	m.Items = m.Items[:0]
	for _, elem := range m.PtrItems {
		if elem != nil {
			elem.ResetCodec()
		}
	}
	m.PtrItems = m.PtrItems[:0]
	if m.Items == nil || m.PtrItems == nil {
		var preCount_3 int
		var preCount_4 int
		pi := 0
		for pi < l {
			ptag, pn := codec.DecodeVarint(data[pi:])
			if pn < 0 {
				break
			}
			pi += pn
			pwt := ptag & 0x7
			pfn := ptag >> 3
			switch pwt {
			case 0:
				_, pn = codec.DecodeVarint(data[pi:])
				if pn < 0 {
					break
				}
				pi += pn
			case 1:
				if pi+8 > l {
					break
				}
				pi += 8
			case 2:
				pvl, pn := codec.DecodeVarint(data[pi:])
				if pn < 0 {
					break
				}
				pi += pn
				if pvl > uint64(l-pi) {
					break
				}
				switch pfn {
				case 3:
					preCount_3++
				case 4:
					preCount_4++
				}
				pi += int(pvl)
			case 5:
				if pi+4 > l {
					break
				}
				pi += 4
			}
		}
		if preCount_3 > 0 && m.Items == nil {
			m.Items = make([]external.External, 0, preCount_3)
		}
		if preCount_4 > 0 && m.PtrItems == nil {
			m.PtrItems = make([]*external.External, 0, preCount_4)
		}
	}
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("field Name (%d): %w", 1, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Name (%d): %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Name (%d): %w", 1, codec.ErrBufferTooShort)
			}
			m.Name = slab[slabOff+i : slabOff+i+int(vLen)]
			i += int(vLen)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("field Item (%d): %w", 2, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Item (%d): %w", 2, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Item (%d): %w", 2, codec.ErrBufferTooShort)
			}
			if m.Item == nil {
				m.Item = new(external.External)
			}
			if err := m.Item.UnmarshalCodecInternal(data[i:i+int(vLen)], slab, slabOff+i); err != nil {
				return fmt.Errorf("field Item (%d): %w", 2, err)
			}
			seenOptional |= 1 << 2
			i += int(vLen)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("field Items (%d): %w", 3, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Items (%d): %w", 3, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Items (%d): %w", 3, codec.ErrBufferTooShort)
			}
			if len(m.Items) < cap(m.Items) {
				m.Items = m.Items[:len(m.Items)+1]
			} else {
				m.Items = append(m.Items, external.External{})
			}
			if err := m.Items[len(m.Items)-1].UnmarshalCodecInternal(data[i:i+int(vLen)], slab, slabOff+i); err != nil {
				return fmt.Errorf("field Items (%d): %w", 3, err)
			}
			i += int(vLen)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("field PtrItems (%d): %w", 4, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field PtrItems (%d): %w", 4, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field PtrItems (%d): %w", 4, codec.ErrBufferTooShort)
			}
			var elem *external.External
			if len(m.PtrItems) < cap(m.PtrItems) {
				m.PtrItems = m.PtrItems[:len(m.PtrItems)+1]
				elem = m.PtrItems[len(m.PtrItems)-1]
				if elem == nil {
					elem = new(external.External)
					m.PtrItems[len(m.PtrItems)-1] = elem
				}
			} else {
				elem = new(external.External)
				m.PtrItems = append(m.PtrItems, elem)
			}
			if err := elem.UnmarshalCodecInternal(data[i:i+int(vLen)], slab, slabOff+i); err != nil {
				return fmt.Errorf("field PtrItems (%d): %w", 4, err)
			}
			i += int(vLen)
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	if seenOptional&(1<<2) == 0 {
		m.Item = nil
	}
	return nil
}

func (m *CrossContainer) ResetCodec() {
	if m == nil {
		return
	}
	m.Name = ""
	if m.Item != nil {
		m.Item.ResetCodec()
	}
	for idx := range m.Items {
		(&m.Items[idx]).ResetCodec()
	}
	m.Items = m.Items[:0]
	for _, elem := range m.PtrItems {
		if elem != nil {
			elem.ResetCodec()
		}
	}
	m.PtrItems = m.PtrItems[:0]
}
