// Code generated by protoc-gen-codec-go. DO NOT EDIT.
// source: lang/go/integration/fixture.proto

package integration

import (
	binary "encoding/binary"
	fmt "fmt"
	codec "go.stealthscale.io/protoc-gen-codec/lang/go/codec"
	strings "strings"
)

func (m *Fixture) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.ID) > 0 {
		l := len(m.ID)
		n += 1 + codec.Sov(uint64(l)) + l
	}
	if m.Kind != 0 {
		n += 1 + codec.Sov(uint64(m.Kind))
	}
	if m.Status != 0 {
		n += 1 + codec.Sov(uint64(m.Status))
	}
	if m.Score != 0 {
		n += 1 + codec.Sov(uint64(m.Score))
	}
	if m.Sequence != 0 {
		n += 1 + codec.Sov(uint64(m.Sequence))
	}
	if m.Enabled {
		n += 2
	}
	if m.Timestamp != 0 {
		n += 1 + codec.Sov(uint64(m.Timestamp))
	}
	if m.Ref != (Digest{}) {
		n += 34
	}
	for _, s := range m.Tags {
		l := len(s)
		n += 1 + codec.Sov(uint64(l)) + l
	}
	if len(m.Data) > 0 {
		l := len(m.Data)
		n += 1 + codec.Sov(uint64(l)) + l
	}
	return n
}

func (m *Fixture) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n, err := m.MarshalToCodec(buf)
	if err != nil {
		return nil, err
	}
	return buf[:n], nil
}

func (m *Fixture) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	n := 0
	if len(m.ID) > 0 {
		buf[n+0] = 0x0a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.ID)))
		n += copy(buf[n:], m.ID)
	}
	if m.Kind != 0 {
		buf[n+0] = 0x10
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Kind))
	}
	if m.Status != 0 {
		buf[n+0] = 0x18
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Status))
	}
	if m.Score != 0 {
		buf[n+0] = 0x20
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Score))
	}
	if m.Sequence != 0 {
		buf[n+0] = 0x28
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Sequence))
	}
	if m.Enabled {
		buf[n+0] = 0x30
		n += 1
		buf[n] = 1
		n++
	}
	if m.Timestamp != 0 {
		buf[n+0] = 0x38
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Timestamp))
	}
	if m.Ref != (Digest{}) {
		buf[n+0] = 0x42
		n += 1
		n += codec.EncodeVarint(buf[n:], 32)
		copy(buf[n:], m.Ref[:])
		n += 32
	}
	for _, s := range m.Tags {
		buf[n+0] = 0x4a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(s)))
		n += copy(buf[n:], s)
	}
	if len(m.Data) > 0 {
		buf[n+0] = 0x52
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.Data)))
		n += copy(buf[n:], m.Data)
	}
	return n, nil
}

func (m *Fixture) UnmarshalCodec(data []byte) error {
	l := len(data)
	i := 0
	m.Tags = m.Tags[:0]
	m.Data = m.Data[:0]
	strTotal := 0
	{
		si := 0
		for si < l {
			stag, sn := codec.DecodeVarint(data[si:])
			if sn < 0 {
				break
			}
			si += sn
			swt := stag & 0x7
			sfn := stag >> 3
			switch swt {
			case 0:
				_, sn = codec.DecodeVarint(data[si:])
				if sn < 0 {
					break
				}
				si += sn
			case 1:
				if si+8 > l {
					break
				}
				si += 8
			case 2:
				svl, sn := codec.DecodeVarint(data[si:])
				if sn < 0 {
					break
				}
				si += sn
				if svl > uint64(l-si) {
					break
				}
				switch sfn {
				case 1:
					strTotal += int(svl)
				case 9:
					strTotal += int(svl)
				}
				si += int(svl)
			case 5:
				if si+4 > l {
					break
				}
				si += 4
			}
		}
	}

	var slab string
	if strTotal > 0 {
		var strSlab strings.Builder
		strSlab.Grow(strTotal)
		{
			si := 0
			for si < l {
				stag, sn := codec.DecodeVarint(data[si:])
				if sn < 0 {
					break
				}
				si += sn
				swt := stag & 0x7
				sfn := stag >> 3
				switch swt {
				case 0:
					_, sn = codec.DecodeVarint(data[si:])
					if sn < 0 {
						break
					}
					si += sn
				case 1:
					if si+8 > l {
						break
					}
					si += 8
				case 2:
					svl, sn := codec.DecodeVarint(data[si:])
					if sn < 0 {
						break
					}
					si += sn
					if svl > uint64(l-si) {
						break
					}
					switch sfn {
					case 1:
						strSlab.Write(data[si : si+int(svl)])
					case 9:
						strSlab.Write(data[si : si+int(svl)])
					}
					si += int(svl)
				case 5:
					if si+4 > l {
						break
					}
					si += 4
				}
			}
		}
		slab = strSlab.String()
	}
	slabOff := 0

	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 2 {
				return codec.ErrInvalidWireType
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field %d: %w", 1, codec.ErrBufferTooShort)
			}
			se := slabOff + int(vLen)
			if se > len(slab) {
				se = len(slab)
			}
			m.ID = slab[slabOff:se]
			slabOff = se
			i += int(vLen)
		case 2:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 2, codec.ErrInvalidVarint)
			}
			i += n
			m.Kind = uint32(v)
		case 3:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 3, codec.ErrInvalidVarint)
			}
			i += n
			m.Status = Status(v)
		case 4:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 4, codec.ErrInvalidVarint)
			}
			i += n
			m.Score = int64(v)
		case 5:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 5, codec.ErrInvalidVarint)
			}
			i += n
			m.Sequence = v
		case 6:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 6, codec.ErrInvalidVarint)
			}
			i += n
			m.Enabled = v != 0
		case 7:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 7, codec.ErrInvalidVarint)
			}
			i += n
			m.Timestamp = int64(v)
		case 8:
			if wireType != 2 {
				return codec.ErrInvalidWireType
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 8, codec.ErrInvalidVarint)
			}
			i += n
			if vLen != 32 {
				return codec.ErrInvalidLength
			}
			if l-i < 32 {
				return fmt.Errorf("field %d: %w", 8, codec.ErrBufferTooShort)
			}
			copy(m.Ref[:], data[i:i+32])
			i += 32
		case 9:
			if wireType != 2 {
				return codec.ErrInvalidWireType
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 9, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field %d: %w", 9, codec.ErrBufferTooShort)
			}
			se := slabOff + int(vLen)
			if se > len(slab) {
				se = len(slab)
			}
			m.Tags = append(m.Tags, slab[slabOff:se])
			slabOff = se
			i += int(vLen)
		case 10:
			if wireType != 2 {
				return codec.ErrInvalidWireType
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 10, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field %d: %w", 10, codec.ErrBufferTooShort)
			}
			m.Data = append(m.Data[:0], data[i:i+int(vLen)]...)
			i += int(vLen)
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *Fixture) ResetCodec() {
	if m == nil {
		return
	}
	m.ID = ""
	m.Kind = 0
	m.Status = 0
	m.Score = 0
	m.Sequence = 0
	m.Enabled = false
	m.Timestamp = 0
	m.Ref = Digest{}
	m.Tags = nil
	m.Data = nil
	if ri, ok := any(m).(interface{ ResetInternal() }); ok {
		ri.ResetInternal()
	}
}

func (m *Patch) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if m.Kind != 0 {
		n += 1 + codec.Sov(uint64(m.Kind))
	}
	if m.VertexID != 0 {
		n += 1 + codec.Sov(uint64(m.VertexID))
	}
	if m.Sequence != 0 {
		n += 1 + codec.Sov(uint64(m.Sequence))
	}
	if m.Source != 0 {
		n += 1 + codec.Sov(uint64(m.Source))
	}
	if len(m.TextVal) > 0 {
		l := len(m.TextVal)
		n += 1 + codec.Sov(uint64(l)) + l
	}
	if m.IntVal != 0 {
		n += 1 + codec.Sov(uint64(m.IntVal))
	}
	if m.Fixed64Val != 0 {
		n += 9
	}
	if m.BlobRef != (Digest{}) {
		n += 34
	}
	return n
}

func (m *Patch) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n, err := m.MarshalToCodec(buf)
	if err != nil {
		return nil, err
	}
	return buf[:n], nil
}

func (m *Patch) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	n := 0
	if m.Kind != 0 {
		buf[n+0] = 0x08
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Kind))
	}
	if m.VertexID != 0 {
		buf[n+0] = 0x10
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.VertexID))
	}
	if m.Sequence != 0 {
		buf[n+0] = 0x18
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Sequence))
	}
	if m.Source != 0 {
		buf[n+0] = 0x20
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Source))
	}
	if len(m.TextVal) > 0 {
		buf[n+0] = 0x2a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.TextVal)))
		n += copy(buf[n:], m.TextVal)
	}
	if m.IntVal != 0 {
		buf[n+0] = 0x30
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.IntVal))
	}
	if m.Fixed64Val != 0 {
		buf[n+0] = 0x39
		n += 1
		binary.LittleEndian.PutUint64(buf[n:], uint64(m.Fixed64Val))
		n += 8
	}
	if m.BlobRef != (Digest{}) {
		buf[n+0] = 0x42
		n += 1
		n += codec.EncodeVarint(buf[n:], 32)
		copy(buf[n:], m.BlobRef[:])
		n += 32
	}
	return n, nil
}

func (m *Patch) UnmarshalCodec(data []byte) error {
	l := len(data)
	i := 0
	strTotal := 0
	{
		si := 0
		for si < l {
			stag, sn := codec.DecodeVarint(data[si:])
			if sn < 0 {
				break
			}
			si += sn
			swt := stag & 0x7
			sfn := stag >> 3
			switch swt {
			case 0:
				_, sn = codec.DecodeVarint(data[si:])
				if sn < 0 {
					break
				}
				si += sn
			case 1:
				if si+8 > l {
					break
				}
				si += 8
			case 2:
				svl, sn := codec.DecodeVarint(data[si:])
				if sn < 0 {
					break
				}
				si += sn
				if svl > uint64(l-si) {
					break
				}
				switch sfn {
				case 5:
					strTotal += int(svl)
				}
				si += int(svl)
			case 5:
				if si+4 > l {
					break
				}
				si += 4
			}
		}
	}

	var slab string
	if strTotal > 0 {
		var strSlab strings.Builder
		strSlab.Grow(strTotal)
		{
			si := 0
			for si < l {
				stag, sn := codec.DecodeVarint(data[si:])
				if sn < 0 {
					break
				}
				si += sn
				swt := stag & 0x7
				sfn := stag >> 3
				switch swt {
				case 0:
					_, sn = codec.DecodeVarint(data[si:])
					if sn < 0 {
						break
					}
					si += sn
				case 1:
					if si+8 > l {
						break
					}
					si += 8
				case 2:
					svl, sn := codec.DecodeVarint(data[si:])
					if sn < 0 {
						break
					}
					si += sn
					if svl > uint64(l-si) {
						break
					}
					switch sfn {
					case 5:
						strSlab.Write(data[si : si+int(svl)])
					}
					si += int(svl)
				case 5:
					if si+4 > l {
						break
					}
					si += 4
				}
			}
		}
		slab = strSlab.String()
	}
	slabOff := 0

	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			m.Kind = PatchKind(v)
		case 2:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 2, codec.ErrInvalidVarint)
			}
			i += n
			m.VertexID = uint32(v)
		case 3:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 3, codec.ErrInvalidVarint)
			}
			i += n
			m.Sequence = v
		case 4:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 4, codec.ErrInvalidVarint)
			}
			i += n
			m.Source = Source(v)
		case 5:
			if wireType != 2 {
				return codec.ErrInvalidWireType
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 5, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field %d: %w", 5, codec.ErrBufferTooShort)
			}
			se := slabOff + int(vLen)
			if se > len(slab) {
				se = len(slab)
			}
			m.TextVal = slab[slabOff:se]
			slabOff = se
			i += int(vLen)
		case 6:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 6, codec.ErrInvalidVarint)
			}
			i += n
			m.IntVal = int64(v)
		case 7:
			if wireType != 1 {
				return codec.ErrInvalidWireType
			}
			if l-i < 8 {
				return fmt.Errorf("field %d: %w", 7, codec.ErrBufferTooShort)
			}
			m.Fixed64Val = Fixed64(binary.LittleEndian.Uint64(data[i:]))
			i += 8
		case 8:
			if wireType != 2 {
				return codec.ErrInvalidWireType
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 8, codec.ErrInvalidVarint)
			}
			i += n
			if vLen != 32 {
				return codec.ErrInvalidLength
			}
			if l-i < 32 {
				return fmt.Errorf("field %d: %w", 8, codec.ErrBufferTooShort)
			}
			copy(m.BlobRef[:], data[i:i+32])
			i += 32
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *Patch) ResetCodec() {
	if m == nil {
		return
	}
	m.Kind = 0
	m.VertexID = 0
	m.Sequence = 0
	m.Source = 0
	m.TextVal = ""
	m.IntVal = 0
	m.Fixed64Val = 0
	m.BlobRef = Digest{}
	if ri, ok := any(m).(interface{ ResetInternal() }); ok {
		ri.ResetInternal()
	}
}

func (m *Evidence) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if m.Kind != 0 {
		n += 1 + codec.Sov(uint64(m.Kind))
	}
	if m.Durability != 0 {
		n += 1 + codec.Sov(uint64(m.Durability))
	}
	if m.Access != 0 {
		n += 1 + codec.Sov(uint64(m.Access))
	}
	if len(m.TraceID) > 0 {
		l := len(m.TraceID)
		n += 1 + codec.Sov(uint64(l)) + l
	}
	if len(m.FederationTraceID) > 0 {
		l := len(m.FederationTraceID)
		n += 1 + codec.Sov(uint64(l)) + l
	}
	if len(m.JobID) > 0 {
		l := len(m.JobID)
		n += 1 + codec.Sov(uint64(l)) + l
	}
	if len(m.ThreadID) > 0 {
		l := len(m.ThreadID)
		n += 1 + codec.Sov(uint64(l)) + l
	}
	if len(m.TenantID) > 0 {
		l := len(m.TenantID)
		n += 1 + codec.Sov(uint64(l)) + l
	}
	if m.TimestampMs != 0 {
		n += 1 + codec.Sov(uint64(m.TimestampMs))
	}
	if m.PayloadRef != (Digest{}) {
		n += 34
	}
	for _, s := range m.Jurisdictions {
		l := len(s)
		n += 1 + codec.Sov(uint64(l)) + l
	}
	if len(m.RetentionPolicyID) > 0 {
		l := len(m.RetentionPolicyID)
		n += 1 + codec.Sov(uint64(l)) + l
	}
	return n
}

func (m *Evidence) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n, err := m.MarshalToCodec(buf)
	if err != nil {
		return nil, err
	}
	return buf[:n], nil
}

func (m *Evidence) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	n := 0
	if m.Kind != 0 {
		buf[n+0] = 0x08
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Kind))
	}
	if m.Durability != 0 {
		buf[n+0] = 0x10
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Durability))
	}
	if m.Access != 0 {
		buf[n+0] = 0x18
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Access))
	}
	if len(m.TraceID) > 0 {
		buf[n+0] = 0x22
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.TraceID)))
		n += copy(buf[n:], m.TraceID)
	}
	if len(m.FederationTraceID) > 0 {
		buf[n+0] = 0x2a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.FederationTraceID)))
		n += copy(buf[n:], m.FederationTraceID)
	}
	if len(m.JobID) > 0 {
		buf[n+0] = 0x32
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.JobID)))
		n += copy(buf[n:], m.JobID)
	}
	if len(m.ThreadID) > 0 {
		buf[n+0] = 0x3a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.ThreadID)))
		n += copy(buf[n:], m.ThreadID)
	}
	if len(m.TenantID) > 0 {
		buf[n+0] = 0x42
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.TenantID)))
		n += copy(buf[n:], m.TenantID)
	}
	if m.TimestampMs != 0 {
		buf[n+0] = 0x48
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.TimestampMs))
	}
	if m.PayloadRef != (Digest{}) {
		buf[n+0] = 0x52
		n += 1
		n += codec.EncodeVarint(buf[n:], 32)
		copy(buf[n:], m.PayloadRef[:])
		n += 32
	}
	for _, s := range m.Jurisdictions {
		buf[n+0] = 0x5a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(s)))
		n += copy(buf[n:], s)
	}
	if len(m.RetentionPolicyID) > 0 {
		buf[n+0] = 0x62
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.RetentionPolicyID)))
		n += copy(buf[n:], m.RetentionPolicyID)
	}
	return n, nil
}

func (m *Evidence) UnmarshalCodec(data []byte) error {
	l := len(data)
	i := 0
	m.Jurisdictions = m.Jurisdictions[:0]
	strTotal := 0
	{
		si := 0
		for si < l {
			stag, sn := codec.DecodeVarint(data[si:])
			if sn < 0 {
				break
			}
			si += sn
			swt := stag & 0x7
			sfn := stag >> 3
			switch swt {
			case 0:
				_, sn = codec.DecodeVarint(data[si:])
				if sn < 0 {
					break
				}
				si += sn
			case 1:
				if si+8 > l {
					break
				}
				si += 8
			case 2:
				svl, sn := codec.DecodeVarint(data[si:])
				if sn < 0 {
					break
				}
				si += sn
				if svl > uint64(l-si) {
					break
				}
				switch sfn {
				case 4:
					strTotal += int(svl)
				case 5:
					strTotal += int(svl)
				case 6:
					strTotal += int(svl)
				case 7:
					strTotal += int(svl)
				case 8:
					strTotal += int(svl)
				case 11:
					strTotal += int(svl)
				case 12:
					strTotal += int(svl)
				}
				si += int(svl)
			case 5:
				if si+4 > l {
					break
				}
				si += 4
			}
		}
	}

	var slab string
	if strTotal > 0 {
		var strSlab strings.Builder
		strSlab.Grow(strTotal)
		{
			si := 0
			for si < l {
				stag, sn := codec.DecodeVarint(data[si:])
				if sn < 0 {
					break
				}
				si += sn
				swt := stag & 0x7
				sfn := stag >> 3
				switch swt {
				case 0:
					_, sn = codec.DecodeVarint(data[si:])
					if sn < 0 {
						break
					}
					si += sn
				case 1:
					if si+8 > l {
						break
					}
					si += 8
				case 2:
					svl, sn := codec.DecodeVarint(data[si:])
					if sn < 0 {
						break
					}
					si += sn
					if svl > uint64(l-si) {
						break
					}
					switch sfn {
					case 4:
						strSlab.Write(data[si : si+int(svl)])
					case 5:
						strSlab.Write(data[si : si+int(svl)])
					case 6:
						strSlab.Write(data[si : si+int(svl)])
					case 7:
						strSlab.Write(data[si : si+int(svl)])
					case 8:
						strSlab.Write(data[si : si+int(svl)])
					case 11:
						strSlab.Write(data[si : si+int(svl)])
					case 12:
						strSlab.Write(data[si : si+int(svl)])
					}
					si += int(svl)
				case 5:
					if si+4 > l {
						break
					}
					si += 4
				}
			}
		}
		slab = strSlab.String()
	}
	slabOff := 0

	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			m.Kind = EvidenceKind(v)
		case 2:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 2, codec.ErrInvalidVarint)
			}
			i += n
			m.Durability = Durability(v)
		case 3:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 3, codec.ErrInvalidVarint)
			}
			i += n
			m.Access = AccessTier(v)
		case 4:
			if wireType != 2 {
				return codec.ErrInvalidWireType
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 4, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field %d: %w", 4, codec.ErrBufferTooShort)
			}
			se := slabOff + int(vLen)
			if se > len(slab) {
				se = len(slab)
			}
			m.TraceID = slab[slabOff:se]
			slabOff = se
			i += int(vLen)
		case 5:
			if wireType != 2 {
				return codec.ErrInvalidWireType
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 5, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field %d: %w", 5, codec.ErrBufferTooShort)
			}
			se := slabOff + int(vLen)
			if se > len(slab) {
				se = len(slab)
			}
			m.FederationTraceID = slab[slabOff:se]
			slabOff = se
			i += int(vLen)
		case 6:
			if wireType != 2 {
				return codec.ErrInvalidWireType
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 6, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field %d: %w", 6, codec.ErrBufferTooShort)
			}
			se := slabOff + int(vLen)
			if se > len(slab) {
				se = len(slab)
			}
			m.JobID = slab[slabOff:se]
			slabOff = se
			i += int(vLen)
		case 7:
			if wireType != 2 {
				return codec.ErrInvalidWireType
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 7, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field %d: %w", 7, codec.ErrBufferTooShort)
			}
			se := slabOff + int(vLen)
			if se > len(slab) {
				se = len(slab)
			}
			m.ThreadID = slab[slabOff:se]
			slabOff = se
			i += int(vLen)
		case 8:
			if wireType != 2 {
				return codec.ErrInvalidWireType
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 8, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field %d: %w", 8, codec.ErrBufferTooShort)
			}
			se := slabOff + int(vLen)
			if se > len(slab) {
				se = len(slab)
			}
			m.TenantID = slab[slabOff:se]
			slabOff = se
			i += int(vLen)
		case 9:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 9, codec.ErrInvalidVarint)
			}
			i += n
			m.TimestampMs = int64(v)
		case 10:
			if wireType != 2 {
				return codec.ErrInvalidWireType
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 10, codec.ErrInvalidVarint)
			}
			i += n
			if vLen != 32 {
				return codec.ErrInvalidLength
			}
			if l-i < 32 {
				return fmt.Errorf("field %d: %w", 10, codec.ErrBufferTooShort)
			}
			copy(m.PayloadRef[:], data[i:i+32])
			i += 32
		case 11:
			if wireType != 2 {
				return codec.ErrInvalidWireType
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 11, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field %d: %w", 11, codec.ErrBufferTooShort)
			}
			se := slabOff + int(vLen)
			if se > len(slab) {
				se = len(slab)
			}
			m.Jurisdictions = append(m.Jurisdictions, slab[slabOff:se])
			slabOff = se
			i += int(vLen)
		case 12:
			if wireType != 2 {
				return codec.ErrInvalidWireType
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 12, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field %d: %w", 12, codec.ErrBufferTooShort)
			}
			se := slabOff + int(vLen)
			if se > len(slab) {
				se = len(slab)
			}
			m.RetentionPolicyID = slab[slabOff:se]
			slabOff = se
			i += int(vLen)
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *Evidence) ResetCodec() {
	if m == nil {
		return
	}
	m.Kind = 0
	m.Durability = 0
	m.Access = 0
	m.TraceID = ""
	m.FederationTraceID = ""
	m.JobID = ""
	m.ThreadID = ""
	m.TenantID = ""
	m.TimestampMs = 0
	m.PayloadRef = Digest{}
	m.Jurisdictions = nil
	m.RetentionPolicyID = ""
	if ri, ok := any(m).(interface{ ResetInternal() }); ok {
		ri.ResetInternal()
	}
}

func (m *Minimal) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.ID) > 0 {
		l := len(m.ID)
		n += 1 + codec.Sov(uint64(l)) + l
	}
	return n
}

func (m *Minimal) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n, err := m.MarshalToCodec(buf)
	if err != nil {
		return nil, err
	}
	return buf[:n], nil
}

func (m *Minimal) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	n := 0
	if len(m.ID) > 0 {
		buf[n+0] = 0x0a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.ID)))
		n += copy(buf[n:], m.ID)
	}
	return n, nil
}

func (m *Minimal) UnmarshalCodec(data []byte) error {
	l := len(data)
	i := 0
	dataStr := string(data)
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 2 {
				return codec.ErrInvalidWireType
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field %d: %w", 1, codec.ErrBufferTooShort)
			}
			m.ID = dataStr[i : i+int(vLen)]
			i += int(vLen)
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *Minimal) ResetCodec() {
	if m == nil {
		return
	}
	m.ID = ""
	if ri, ok := any(m).(interface{ ResetInternal() }); ok {
		ri.ResetInternal()
	}
}

func (m *NumericOnly) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if m.A != 0 {
		n += 1 + codec.Sov(uint64(m.A))
	}
	if m.B != 0 {
		n += 1 + codec.Sov(uint64(m.B))
	}
	if m.C != 0 {
		n += 1 + codec.Sov(uint64(m.C))
	}
	if m.D != 0 {
		n += 9
	}
	if m.E {
		n += 2
	}
	return n
}

func (m *NumericOnly) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n, err := m.MarshalToCodec(buf)
	if err != nil {
		return nil, err
	}
	return buf[:n], nil
}

func (m *NumericOnly) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	n := 0
	if m.A != 0 {
		buf[n+0] = 0x08
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.A))
	}
	if m.B != 0 {
		buf[n+0] = 0x10
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.B))
	}
	if m.C != 0 {
		buf[n+0] = 0x18
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.C))
	}
	if m.D != 0 {
		buf[n+0] = 0x21
		n += 1
		binary.LittleEndian.PutUint64(buf[n:], uint64(m.D))
		n += 8
	}
	if m.E {
		buf[n+0] = 0x28
		n += 1
		buf[n] = 1
		n++
	}
	return n, nil
}

func (m *NumericOnly) UnmarshalCodec(data []byte) error {
	l := len(data)
	i := 0
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			m.A = uint32(v)
		case 2:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 2, codec.ErrInvalidVarint)
			}
			i += n
			m.B = v
		case 3:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 3, codec.ErrInvalidVarint)
			}
			i += n
			m.C = int64(v)
		case 4:
			if wireType != 1 {
				return codec.ErrInvalidWireType
			}
			if l-i < 8 {
				return fmt.Errorf("field %d: %w", 4, codec.ErrBufferTooShort)
			}
			m.D = Fixed64(binary.LittleEndian.Uint64(data[i:]))
			i += 8
		case 5:
			if wireType != 0 {
				return codec.ErrInvalidWireType
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field %d: %w", 5, codec.ErrInvalidVarint)
			}
			i += n
			m.E = v != 0
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *NumericOnly) ResetCodec() {
	if m == nil {
		return
	}
	m.A = 0
	m.B = 0
	m.C = 0
	m.D = 0
	m.E = false
	if ri, ok := any(m).(interface{ ResetInternal() }); ok {
		ri.ResetInternal()
	}
}
