// Code generated by protoc-gen-codec-go. DO NOT EDIT.
// source: lang/go/integration/fixture.proto

package integration

import (
	binary "encoding/binary"
	fmt "fmt"
	codec "go.stealthscale.io/protoc-gen-codec/lang/go/codec"
	slices "slices"
	time "time"
)

func (m *Fixture) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.ID) > 0 {
		l := len(m.ID)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	if m.Kind != 0 {
		n += 1 + codec.SizeVarint(uint64(m.Kind))
	}
	if m.Status != 0 {
		n += 1 + codec.SizeVarint(uint64(m.Status))
	}
	if m.Score != 0 {
		n += 1 + codec.SizeVarint(uint64(m.Score))
	}
	if m.Sequence != 0 {
		n += 1 + codec.SizeVarint(uint64(m.Sequence))
	}
	if m.Enabled {
		n += 2
	}
	if m.Timestamp != 0 {
		n += 1 + codec.SizeVarint(uint64(m.Timestamp))
	}
	if m.Ref != (Digest{}) {
		n += 34
	}
	for _, s := range m.Tags {
		l := len(s)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	if len(m.Data) > 0 {
		l := len(m.Data)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	return n
}

func (m *Fixture) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n := m.MarshalCodecInternal(buf)
	return buf[:n], nil
}

func (m *Fixture) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeCodec() {
		return 0, codec.ErrBufferTooShort
	}
	return m.MarshalCodecInternal(buf), nil
}

func (m *Fixture) MarshalCodecInternal(buf []byte) int {
	n := 0
	if len(m.ID) > 0 {
		buf[n+0] = 0x0a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.ID)))
		n += copy(buf[n:], m.ID)
	}
	if m.Kind != 0 {
		buf[n+0] = 0x10
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Kind))
	}
	if m.Status != 0 {
		buf[n+0] = 0x18
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Status))
	}
	if m.Score != 0 {
		buf[n+0] = 0x20
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Score))
	}
	if m.Sequence != 0 {
		buf[n+0] = 0x28
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Sequence))
	}
	if m.Enabled {
		buf[n+0] = 0x30
		n += 1
		buf[n] = 1
		n++
	}
	if m.Timestamp != 0 {
		buf[n+0] = 0x38
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Timestamp))
	}
	if m.Ref != (Digest{}) {
		buf[n+0] = 0x42
		n += 1
		n += codec.EncodeVarint(buf[n:], 32)
		copy(buf[n:], m.Ref[:])
		n += 32
	}
	for _, s := range m.Tags {
		buf[n+0] = 0x4a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(s)))
		n += copy(buf[n:], s)
	}
	if len(m.Data) > 0 {
		buf[n+0] = 0x52
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.Data)))
		n += copy(buf[n:], m.Data)
	}
	return n
}

func (m *Fixture) UnmarshalCodec(data []byte) error {
	return m.UnmarshalCodecInternal(data, string(data), 0)
}

func (m *Fixture) UnmarshalCodecInternal(data []byte, slab string, slabOff int) error {
	_ = slab
	_ = slabOff
	l := len(data)
	i := 0
	m.ID = ""
	m.Kind = 0
	m.Status = 0
	m.Score = 0
	m.Sequence = 0
	m.Enabled = false
	m.Timestamp = 0
	m.Ref = Digest{}
	m.Tags = m.Tags[:0]
	m.Data = m.Data[:0]
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("field ID (%d): %w", 1, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field ID (%d): %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field ID (%d): %w", 1, codec.ErrBufferTooShort)
			}
			m.ID = slab[slabOff+i : slabOff+i+int(vLen)]
			i += int(vLen)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("field Kind (%d): %w", 2, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Kind (%d): %w", 2, codec.ErrInvalidVarint)
			}
			i += n
			m.Kind = uint32(v)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("field Status (%d): %w", 3, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Status (%d): %w", 3, codec.ErrInvalidVarint)
			}
			i += n
			m.Status = Status(v)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("field Score (%d): %w", 4, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Score (%d): %w", 4, codec.ErrInvalidVarint)
			}
			i += n
			m.Score = int64(v)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("field Sequence (%d): %w", 5, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Sequence (%d): %w", 5, codec.ErrInvalidVarint)
			}
			i += n
			m.Sequence = v
		case 6:
			if wireType != 0 {
				return fmt.Errorf("field Enabled (%d): %w", 6, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Enabled (%d): %w", 6, codec.ErrInvalidVarint)
			}
			i += n
			m.Enabled = v != 0
		case 7:
			if wireType != 0 {
				return fmt.Errorf("field Timestamp (%d): %w", 7, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Timestamp (%d): %w", 7, codec.ErrInvalidVarint)
			}
			i += n
			m.Timestamp = int64(v)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("field Ref (%d): %w", 8, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Ref (%d): %w", 8, codec.ErrInvalidVarint)
			}
			i += n
			if vLen != 32 {
				return fmt.Errorf("field Ref (%d): %w", 8, codec.ErrInvalidLength)
			}
			if l-i < 32 {
				return fmt.Errorf("field Ref (%d): %w", 8, codec.ErrBufferTooShort)
			}
			copy(m.Ref[:], data[i:i+32])
			i += 32
		case 9:
			if wireType != 2 {
				return fmt.Errorf("field Tags (%d): %w", 9, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Tags (%d): %w", 9, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Tags (%d): %w", 9, codec.ErrBufferTooShort)
			}
			m.Tags = append(m.Tags, slab[slabOff+i:slabOff+i+int(vLen)])
			i += int(vLen)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("field Data (%d): %w", 10, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Data (%d): %w", 10, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Data (%d): %w", 10, codec.ErrBufferTooShort)
			}
			m.Data = append(m.Data[:0], data[i:i+int(vLen)]...)
			i += int(vLen)
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *Fixture) ResetCodec() {
	if m == nil {
		return
	}
	m.ID = ""
	m.Kind = 0
	m.Status = 0
	m.Score = 0
	m.Sequence = 0
	m.Enabled = false
	m.Timestamp = 0
	m.Ref = Digest{}
	m.Tags = m.Tags[:0]
	m.Data = m.Data[:0]
}

func (m *Patch) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if m.Kind != 0 {
		n += 1 + codec.SizeVarint(uint64(m.Kind))
	}
	if m.VertexID != 0 {
		n += 1 + codec.SizeVarint(uint64(m.VertexID))
	}
	if m.Sequence != 0 {
		n += 1 + codec.SizeVarint(uint64(m.Sequence))
	}
	if m.Source != 0 {
		n += 1 + codec.SizeVarint(uint64(m.Source))
	}
	if len(m.TextVal) > 0 {
		l := len(m.TextVal)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	if m.IntVal != 0 {
		n += 1 + codec.SizeVarint(uint64(m.IntVal))
	}
	if m.Fixed64Val != 0 {
		n += 9
	}
	if m.BlobRef != (Digest{}) {
		n += 34
	}
	return n
}

func (m *Patch) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n := m.MarshalCodecInternal(buf)
	return buf[:n], nil
}

func (m *Patch) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeCodec() {
		return 0, codec.ErrBufferTooShort
	}
	return m.MarshalCodecInternal(buf), nil
}

func (m *Patch) MarshalCodecInternal(buf []byte) int {
	n := 0
	if m.Kind != 0 {
		buf[n+0] = 0x08
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Kind))
	}
	if m.VertexID != 0 {
		buf[n+0] = 0x10
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.VertexID))
	}
	if m.Sequence != 0 {
		buf[n+0] = 0x18
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Sequence))
	}
	if m.Source != 0 {
		buf[n+0] = 0x20
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Source))
	}
	if len(m.TextVal) > 0 {
		buf[n+0] = 0x2a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.TextVal)))
		n += copy(buf[n:], m.TextVal)
	}
	if m.IntVal != 0 {
		buf[n+0] = 0x30
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.IntVal))
	}
	if m.Fixed64Val != 0 {
		buf[n+0] = 0x39
		n += 1
		binary.LittleEndian.PutUint64(buf[n:], uint64(m.Fixed64Val))
		n += 8
	}
	if m.BlobRef != (Digest{}) {
		buf[n+0] = 0x42
		n += 1
		n += codec.EncodeVarint(buf[n:], 32)
		copy(buf[n:], m.BlobRef[:])
		n += 32
	}
	return n
}

func (m *Patch) UnmarshalCodec(data []byte) error {
	return m.UnmarshalCodecInternal(data, string(data), 0)
}

func (m *Patch) UnmarshalCodecInternal(data []byte, slab string, slabOff int) error {
	_ = slab
	_ = slabOff
	l := len(data)
	i := 0
	m.Kind = 0
	m.VertexID = 0
	m.Sequence = 0
	m.Source = 0
	m.TextVal = ""
	m.IntVal = 0
	m.Fixed64Val = 0
	m.BlobRef = Digest{}
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("field Kind (%d): %w", 1, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Kind (%d): %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			m.Kind = PatchKind(v)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("field VertexID (%d): %w", 2, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field VertexID (%d): %w", 2, codec.ErrInvalidVarint)
			}
			i += n
			m.VertexID = uint32(v)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("field Sequence (%d): %w", 3, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Sequence (%d): %w", 3, codec.ErrInvalidVarint)
			}
			i += n
			m.Sequence = v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("field Source (%d): %w", 4, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Source (%d): %w", 4, codec.ErrInvalidVarint)
			}
			i += n
			m.Source = Source(v)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("field TextVal (%d): %w", 5, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field TextVal (%d): %w", 5, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field TextVal (%d): %w", 5, codec.ErrBufferTooShort)
			}
			m.TextVal = slab[slabOff+i : slabOff+i+int(vLen)]
			i += int(vLen)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("field IntVal (%d): %w", 6, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field IntVal (%d): %w", 6, codec.ErrInvalidVarint)
			}
			i += n
			m.IntVal = int64(v)
		case 7:
			if wireType != 1 {
				return fmt.Errorf("field Fixed64Val (%d): %w", 7, codec.ErrInvalidWireType)
			}
			if l-i < 8 {
				return fmt.Errorf("field Fixed64Val (%d): %w", 7, codec.ErrBufferTooShort)
			}
			m.Fixed64Val = Fixed64(binary.LittleEndian.Uint64(data[i:]))
			i += 8
		case 8:
			if wireType != 2 {
				return fmt.Errorf("field BlobRef (%d): %w", 8, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field BlobRef (%d): %w", 8, codec.ErrInvalidVarint)
			}
			i += n
			if vLen != 32 {
				return fmt.Errorf("field BlobRef (%d): %w", 8, codec.ErrInvalidLength)
			}
			if l-i < 32 {
				return fmt.Errorf("field BlobRef (%d): %w", 8, codec.ErrBufferTooShort)
			}
			copy(m.BlobRef[:], data[i:i+32])
			i += 32
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *Patch) ResetCodec() {
	if m == nil {
		return
	}
	m.Kind = 0
	m.VertexID = 0
	m.Sequence = 0
	m.Source = 0
	m.TextVal = ""
	m.IntVal = 0
	m.Fixed64Val = 0
	m.BlobRef = Digest{}
}

func (m *Evidence) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if m.Kind != 0 {
		n += 1 + codec.SizeVarint(uint64(m.Kind))
	}
	if m.Durability != 0 {
		n += 1 + codec.SizeVarint(uint64(m.Durability))
	}
	if m.Access != 0 {
		n += 1 + codec.SizeVarint(uint64(m.Access))
	}
	if len(m.TraceID) > 0 {
		l := len(m.TraceID)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	if len(m.FederationTraceID) > 0 {
		l := len(m.FederationTraceID)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	if len(m.JobID) > 0 {
		l := len(m.JobID)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	if len(m.ThreadID) > 0 {
		l := len(m.ThreadID)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	if len(m.TenantID) > 0 {
		l := len(m.TenantID)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	if m.TimestampMs != 0 {
		n += 1 + codec.SizeVarint(uint64(m.TimestampMs))
	}
	if m.PayloadRef != (Digest{}) {
		n += 34
	}
	for _, s := range m.Jurisdictions {
		l := len(s)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	if len(m.RetentionPolicyID) > 0 {
		l := len(m.RetentionPolicyID)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	return n
}

func (m *Evidence) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n := m.MarshalCodecInternal(buf)
	return buf[:n], nil
}

func (m *Evidence) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeCodec() {
		return 0, codec.ErrBufferTooShort
	}
	return m.MarshalCodecInternal(buf), nil
}

func (m *Evidence) MarshalCodecInternal(buf []byte) int {
	n := 0
	if m.Kind != 0 {
		buf[n+0] = 0x08
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Kind))
	}
	if m.Durability != 0 {
		buf[n+0] = 0x10
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Durability))
	}
	if m.Access != 0 {
		buf[n+0] = 0x18
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Access))
	}
	if len(m.TraceID) > 0 {
		buf[n+0] = 0x22
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.TraceID)))
		n += copy(buf[n:], m.TraceID)
	}
	if len(m.FederationTraceID) > 0 {
		buf[n+0] = 0x2a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.FederationTraceID)))
		n += copy(buf[n:], m.FederationTraceID)
	}
	if len(m.JobID) > 0 {
		buf[n+0] = 0x32
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.JobID)))
		n += copy(buf[n:], m.JobID)
	}
	if len(m.ThreadID) > 0 {
		buf[n+0] = 0x3a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.ThreadID)))
		n += copy(buf[n:], m.ThreadID)
	}
	if len(m.TenantID) > 0 {
		buf[n+0] = 0x42
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.TenantID)))
		n += copy(buf[n:], m.TenantID)
	}
	if m.TimestampMs != 0 {
		buf[n+0] = 0x48
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.TimestampMs))
	}
	if m.PayloadRef != (Digest{}) {
		buf[n+0] = 0x52
		n += 1
		n += codec.EncodeVarint(buf[n:], 32)
		copy(buf[n:], m.PayloadRef[:])
		n += 32
	}
	for _, s := range m.Jurisdictions {
		buf[n+0] = 0x5a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(s)))
		n += copy(buf[n:], s)
	}
	if len(m.RetentionPolicyID) > 0 {
		buf[n+0] = 0x62
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.RetentionPolicyID)))
		n += copy(buf[n:], m.RetentionPolicyID)
	}
	return n
}

func (m *Evidence) UnmarshalCodec(data []byte) error {
	return m.UnmarshalCodecInternal(data, string(data), 0)
}

func (m *Evidence) UnmarshalCodecInternal(data []byte, slab string, slabOff int) error {
	_ = slab
	_ = slabOff
	l := len(data)
	i := 0
	m.Kind = 0
	m.Durability = 0
	m.Access = 0
	m.TraceID = ""
	m.FederationTraceID = ""
	m.JobID = ""
	m.ThreadID = ""
	m.TenantID = ""
	m.TimestampMs = 0
	m.PayloadRef = Digest{}
	m.Jurisdictions = m.Jurisdictions[:0]
	m.RetentionPolicyID = ""
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("field Kind (%d): %w", 1, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Kind (%d): %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			m.Kind = EvidenceKind(v)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("field Durability (%d): %w", 2, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Durability (%d): %w", 2, codec.ErrInvalidVarint)
			}
			i += n
			m.Durability = Durability(v)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("field Access (%d): %w", 3, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Access (%d): %w", 3, codec.ErrInvalidVarint)
			}
			i += n
			m.Access = AccessTier(v)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("field TraceID (%d): %w", 4, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field TraceID (%d): %w", 4, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field TraceID (%d): %w", 4, codec.ErrBufferTooShort)
			}
			m.TraceID = slab[slabOff+i : slabOff+i+int(vLen)]
			i += int(vLen)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("field FederationTraceID (%d): %w", 5, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field FederationTraceID (%d): %w", 5, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field FederationTraceID (%d): %w", 5, codec.ErrBufferTooShort)
			}
			m.FederationTraceID = slab[slabOff+i : slabOff+i+int(vLen)]
			i += int(vLen)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("field JobID (%d): %w", 6, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field JobID (%d): %w", 6, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field JobID (%d): %w", 6, codec.ErrBufferTooShort)
			}
			m.JobID = slab[slabOff+i : slabOff+i+int(vLen)]
			i += int(vLen)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("field ThreadID (%d): %w", 7, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field ThreadID (%d): %w", 7, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field ThreadID (%d): %w", 7, codec.ErrBufferTooShort)
			}
			m.ThreadID = slab[slabOff+i : slabOff+i+int(vLen)]
			i += int(vLen)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("field TenantID (%d): %w", 8, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field TenantID (%d): %w", 8, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field TenantID (%d): %w", 8, codec.ErrBufferTooShort)
			}
			m.TenantID = slab[slabOff+i : slabOff+i+int(vLen)]
			i += int(vLen)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("field TimestampMs (%d): %w", 9, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field TimestampMs (%d): %w", 9, codec.ErrInvalidVarint)
			}
			i += n
			m.TimestampMs = int64(v)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("field PayloadRef (%d): %w", 10, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field PayloadRef (%d): %w", 10, codec.ErrInvalidVarint)
			}
			i += n
			if vLen != 32 {
				return fmt.Errorf("field PayloadRef (%d): %w", 10, codec.ErrInvalidLength)
			}
			if l-i < 32 {
				return fmt.Errorf("field PayloadRef (%d): %w", 10, codec.ErrBufferTooShort)
			}
			copy(m.PayloadRef[:], data[i:i+32])
			i += 32
		case 11:
			if wireType != 2 {
				return fmt.Errorf("field Jurisdictions (%d): %w", 11, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Jurisdictions (%d): %w", 11, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Jurisdictions (%d): %w", 11, codec.ErrBufferTooShort)
			}
			m.Jurisdictions = append(m.Jurisdictions, slab[slabOff+i:slabOff+i+int(vLen)])
			i += int(vLen)
		case 12:
			if wireType != 2 {
				return fmt.Errorf("field RetentionPolicyID (%d): %w", 12, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field RetentionPolicyID (%d): %w", 12, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field RetentionPolicyID (%d): %w", 12, codec.ErrBufferTooShort)
			}
			m.RetentionPolicyID = slab[slabOff+i : slabOff+i+int(vLen)]
			i += int(vLen)
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *Evidence) ResetCodec() {
	if m == nil {
		return
	}
	m.Kind = 0
	m.Durability = 0
	m.Access = 0
	m.TraceID = ""
	m.FederationTraceID = ""
	m.JobID = ""
	m.ThreadID = ""
	m.TenantID = ""
	m.TimestampMs = 0
	m.PayloadRef = Digest{}
	m.Jurisdictions = m.Jurisdictions[:0]
	m.RetentionPolicyID = ""
}

func (m *Minimal) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.ID) > 0 {
		l := len(m.ID)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	return n
}

func (m *Minimal) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n := m.MarshalCodecInternal(buf)
	return buf[:n], nil
}

func (m *Minimal) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeCodec() {
		return 0, codec.ErrBufferTooShort
	}
	return m.MarshalCodecInternal(buf), nil
}

func (m *Minimal) MarshalCodecInternal(buf []byte) int {
	n := 0
	if len(m.ID) > 0 {
		buf[n+0] = 0x0a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.ID)))
		n += copy(buf[n:], m.ID)
	}
	return n
}

func (m *Minimal) UnmarshalCodec(data []byte) error {
	return m.UnmarshalCodecInternal(data, string(data), 0)
}

func (m *Minimal) UnmarshalCodecInternal(data []byte, slab string, slabOff int) error {
	_ = slab
	_ = slabOff
	l := len(data)
	i := 0
	m.ID = ""
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("field ID (%d): %w", 1, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field ID (%d): %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field ID (%d): %w", 1, codec.ErrBufferTooShort)
			}
			m.ID = slab[slabOff+i : slabOff+i+int(vLen)]
			i += int(vLen)
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *Minimal) ResetCodec() {
	if m == nil {
		return
	}
	m.ID = ""
}

func (m *NumericOnly) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if m.A != 0 {
		n += 1 + codec.SizeVarint(uint64(m.A))
	}
	if m.B != 0 {
		n += 1 + codec.SizeVarint(uint64(m.B))
	}
	if m.C != 0 {
		n += 1 + codec.SizeVarint(uint64(m.C))
	}
	if m.D != 0 {
		n += 9
	}
	if m.E {
		n += 2
	}
	if m.F != 0 {
		n += 1 + codec.SizeVarint(uint64(codec.ZigzagEncode32(int32(m.F))))
	}
	if m.G != 0 {
		n += 1 + codec.SizeVarint(codec.ZigzagEncode64(int64(m.G)))
	}
	if m.H != nil {
		n += 1 + codec.SizeVarint(uint64(*m.H))
	}
	if m.I != nil {
		n += 2
	}
	if m.J != nil {
		n += 9
	}
	return n
}

func (m *NumericOnly) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n := m.MarshalCodecInternal(buf)
	return buf[:n], nil
}

func (m *NumericOnly) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeCodec() {
		return 0, codec.ErrBufferTooShort
	}
	return m.MarshalCodecInternal(buf), nil
}

func (m *NumericOnly) MarshalCodecInternal(buf []byte) int {
	n := 0
	if m.A != 0 {
		buf[n+0] = 0x08
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.A))
	}
	if m.B != 0 {
		buf[n+0] = 0x10
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.B))
	}
	if m.C != 0 {
		buf[n+0] = 0x18
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.C))
	}
	if m.D != 0 {
		buf[n+0] = 0x21
		n += 1
		binary.LittleEndian.PutUint64(buf[n:], uint64(m.D))
		n += 8
	}
	if m.E {
		buf[n+0] = 0x28
		n += 1
		buf[n] = 1
		n++
	}
	if m.F != 0 {
		buf[n+0] = 0x30
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(codec.ZigzagEncode32(int32(m.F))))
	}
	if m.G != 0 {
		buf[n+0] = 0x38
		n += 1
		n += codec.EncodeVarint(buf[n:], codec.ZigzagEncode64(int64(m.G)))
	}
	if m.H != nil {
		buf[n+0] = 0x40
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(*m.H))
	}
	if m.I != nil {
		buf[n+0] = 0x48
		n += 1
		if *m.I {
			buf[n] = 1
		} else {
			buf[n] = 0
		}
		n++
	}
	if m.J != nil {
		buf[n+0] = 0x51
		n += 1
		binary.LittleEndian.PutUint64(buf[n:], uint64(*m.J))
		n += 8
	}
	return n
}

func (m *NumericOnly) UnmarshalCodec(data []byte) error {
	return m.UnmarshalCodecInternal(data, "", 0)
}

func (m *NumericOnly) UnmarshalCodecInternal(data []byte, slab string, slabOff int) error {
	_ = slab
	_ = slabOff
	l := len(data)
	i := 0
	var seenOptional uint64
	m.A = 0
	m.B = 0
	m.C = 0
	m.D = 0
	m.E = false
	m.F = 0
	m.G = 0
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("field A (%d): %w", 1, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field A (%d): %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			m.A = uint32(v)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("field B (%d): %w", 2, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field B (%d): %w", 2, codec.ErrInvalidVarint)
			}
			i += n
			m.B = v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("field C (%d): %w", 3, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field C (%d): %w", 3, codec.ErrInvalidVarint)
			}
			i += n
			m.C = int64(v)
		case 4:
			if wireType != 1 {
				return fmt.Errorf("field D (%d): %w", 4, codec.ErrInvalidWireType)
			}
			if l-i < 8 {
				return fmt.Errorf("field D (%d): %w", 4, codec.ErrBufferTooShort)
			}
			m.D = Fixed64(binary.LittleEndian.Uint64(data[i:]))
			i += 8
		case 5:
			if wireType != 0 {
				return fmt.Errorf("field E (%d): %w", 5, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field E (%d): %w", 5, codec.ErrInvalidVarint)
			}
			i += n
			m.E = v != 0
		case 6:
			if wireType != 0 {
				return fmt.Errorf("field F (%d): %w", 6, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field F (%d): %w", 6, codec.ErrInvalidVarint)
			}
			i += n
			m.F = codec.ZigzagDecode32(uint32(v))
		case 7:
			if wireType != 0 {
				return fmt.Errorf("field G (%d): %w", 7, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field G (%d): %w", 7, codec.ErrInvalidVarint)
			}
			i += n
			m.G = codec.ZigzagDecode64(v)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("field H (%d): %w", 8, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field H (%d): %w", 8, codec.ErrInvalidVarint)
			}
			i += n
			if m.H == nil {
				m.H = new(int32)
			}
			*m.H = int32(v)
			seenOptional |= 1 << 8
		case 9:
			if wireType != 0 {
				return fmt.Errorf("field I (%d): %w", 9, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field I (%d): %w", 9, codec.ErrInvalidVarint)
			}
			i += n
			if m.I == nil {
				m.I = new(bool)
			}
			*m.I = v != 0
			seenOptional |= 1 << 9
		case 10:
			if wireType != 1 {
				return fmt.Errorf("field J (%d): %w", 10, codec.ErrInvalidWireType)
			}
			if l-i < 8 {
				return fmt.Errorf("field J (%d): %w", 10, codec.ErrBufferTooShort)
			}
			if m.J == nil {
				m.J = new(Fixed64)
			}
			*m.J = Fixed64(binary.LittleEndian.Uint64(data[i:]))
			seenOptional |= 1 << 10
			i += 8
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	if seenOptional&(1<<8) == 0 {
		m.H = nil
	}
	if seenOptional&(1<<9) == 0 {
		m.I = nil
	}
	if seenOptional&(1<<10) == 0 {
		m.J = nil
	}
	return nil
}

func (m *NumericOnly) ResetCodec() {
	if m == nil {
		return
	}
	m.A = 0
	m.B = 0
	m.C = 0
	m.D = 0
	m.E = false
	m.F = 0
	m.G = 0
	m.H = nil
	m.I = nil
	m.J = nil
}

func (m *PackedZigzag) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.Values32) > 0 {
		l := 0
		for _, v := range m.Values32 {
			l += codec.SizeVarint(uint64(codec.ZigzagEncode32(int32(v))))
		}
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	if len(m.Values64) > 0 {
		l := 0
		for _, v := range m.Values64 {
			l += codec.SizeVarint(codec.ZigzagEncode64(int64(v)))
		}
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	return n
}

func (m *PackedZigzag) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n := m.MarshalCodecInternal(buf)
	return buf[:n], nil
}

func (m *PackedZigzag) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeCodec() {
		return 0, codec.ErrBufferTooShort
	}
	return m.MarshalCodecInternal(buf), nil
}

func (m *PackedZigzag) MarshalCodecInternal(buf []byte) int {
	n := 0
	if len(m.Values32) > 0 {
		buf[n+0] = 0x0a
		n += 1
		l := 0
		for _, v := range m.Values32 {
			l += codec.SizeVarint(uint64(codec.ZigzagEncode32(int32(v))))
		}
		n += codec.EncodeVarint(buf[n:], uint64(l))
		for _, v := range m.Values32 {
			n += codec.EncodeVarint(buf[n:], uint64(codec.ZigzagEncode32(int32(v))))
		}
	}
	if len(m.Values64) > 0 {
		buf[n+0] = 0x12
		n += 1
		l := 0
		for _, v := range m.Values64 {
			l += codec.SizeVarint(codec.ZigzagEncode64(int64(v)))
		}
		n += codec.EncodeVarint(buf[n:], uint64(l))
		for _, v := range m.Values64 {
			n += codec.EncodeVarint(buf[n:], codec.ZigzagEncode64(int64(v)))
		}
	}
	return n
}

func (m *PackedZigzag) UnmarshalCodec(data []byte) error {
	return m.UnmarshalCodecInternal(data, "", 0)
}

func (m *PackedZigzag) UnmarshalCodecInternal(data []byte, slab string, slabOff int) error {
	_ = slab
	_ = slabOff
	l := len(data)
	i := 0
	m.Values32 = m.Values32[:0]
	m.Values64 = m.Values64[:0]
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType == 2 {
				pLen, n := codec.DecodeVarint(data[i:])
				if n < 0 {
					return fmt.Errorf("field Values32 (%d): %w", 1, codec.ErrInvalidVarint)
				}
				i += n
				if pLen > uint64(l-i) {
					return fmt.Errorf("field Values32 (%d): %w", 1, codec.ErrBufferTooShort)
				}
				end := i + int(pLen)
				if m.Values32 == nil {
					m.Values32 = make([]int32, 0, int(pLen))
				}
				for i < end {
					v, n := codec.DecodeVarint(data[i:])
					if n < 0 {
						return fmt.Errorf("field Values32 (%d): %w", 1, codec.ErrInvalidVarint)
					}
					i += n
					m.Values32 = append(m.Values32, codec.ZigzagDecode32(uint32(v)))
				}
			} else if wireType == 0 {
				v, n := codec.DecodeVarint(data[i:])
				if n < 0 {
					return fmt.Errorf("field Values32 (%d): %w", 1, codec.ErrInvalidVarint)
				}
				i += n
				m.Values32 = append(m.Values32, codec.ZigzagDecode32(uint32(v)))
			} else {
				return fmt.Errorf("field Values32 (%d): %w", 1, codec.ErrInvalidWireType)
			}
		case 2:
			if wireType == 2 {
				pLen, n := codec.DecodeVarint(data[i:])
				if n < 0 {
					return fmt.Errorf("field Values64 (%d): %w", 2, codec.ErrInvalidVarint)
				}
				i += n
				if pLen > uint64(l-i) {
					return fmt.Errorf("field Values64 (%d): %w", 2, codec.ErrBufferTooShort)
				}
				end := i + int(pLen)
				if m.Values64 == nil {
					m.Values64 = make([]int64, 0, int(pLen))
				}
				for i < end {
					v, n := codec.DecodeVarint(data[i:])
					if n < 0 {
						return fmt.Errorf("field Values64 (%d): %w", 2, codec.ErrInvalidVarint)
					}
					i += n
					m.Values64 = append(m.Values64, codec.ZigzagDecode64(v))
				}
			} else if wireType == 0 {
				v, n := codec.DecodeVarint(data[i:])
				if n < 0 {
					return fmt.Errorf("field Values64 (%d): %w", 2, codec.ErrInvalidVarint)
				}
				i += n
				m.Values64 = append(m.Values64, codec.ZigzagDecode64(v))
			} else {
				return fmt.Errorf("field Values64 (%d): %w", 2, codec.ErrInvalidWireType)
			}
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *PackedZigzag) ResetCodec() {
	if m == nil {
		return
	}
	m.Values32 = m.Values32[:0]
	m.Values64 = m.Values64[:0]
}

func (m *Inner) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.Label) > 0 {
		l := len(m.Label)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	if m.Count != 0 {
		n += 1 + codec.SizeVarint(uint64(m.Count))
	}
	return n
}

func (m *Inner) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n := m.MarshalCodecInternal(buf)
	return buf[:n], nil
}

func (m *Inner) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeCodec() {
		return 0, codec.ErrBufferTooShort
	}
	return m.MarshalCodecInternal(buf), nil
}

func (m *Inner) MarshalCodecInternal(buf []byte) int {
	n := 0
	if len(m.Label) > 0 {
		buf[n+0] = 0x0a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.Label)))
		n += copy(buf[n:], m.Label)
	}
	if m.Count != 0 {
		buf[n+0] = 0x10
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Count))
	}
	return n
}

func (m *Inner) UnmarshalCodec(data []byte) error {
	return m.UnmarshalCodecInternal(data, string(data), 0)
}

func (m *Inner) UnmarshalCodecInternal(data []byte, slab string, slabOff int) error {
	_ = slab
	_ = slabOff
	l := len(data)
	i := 0
	m.Label = ""
	m.Count = 0
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("field Label (%d): %w", 1, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Label (%d): %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Label (%d): %w", 1, codec.ErrBufferTooShort)
			}
			m.Label = slab[slabOff+i : slabOff+i+int(vLen)]
			i += int(vLen)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("field Count (%d): %w", 2, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Count (%d): %w", 2, codec.ErrInvalidVarint)
			}
			i += n
			m.Count = int64(v)
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *Inner) ResetCodec() {
	if m == nil {
		return
	}
	m.Label = ""
	m.Count = 0
}

func (m *Container) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.Name) > 0 {
		l := len(m.Name)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	if m.Inner != nil {
		if sz := m.Inner.SizeCodec(); sz > 0 {
			n += 1 + codec.SizeVarint(uint64(sz)) + sz
		}
	}
	for _, elem := range m.Children {
		if elem == nil {
			continue
		}
		sz := elem.SizeCodec()
		n += 1 + codec.SizeVarint(uint64(sz)) + sz
	}
	return n
}

func (m *Container) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n := m.MarshalCodecInternal(buf)
	return buf[:n], nil
}

func (m *Container) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeCodec() {
		return 0, codec.ErrBufferTooShort
	}
	return m.MarshalCodecInternal(buf), nil
}

func (m *Container) MarshalCodecInternal(buf []byte) int {
	n := 0
	if len(m.Name) > 0 {
		buf[n+0] = 0x0a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.Name)))
		n += copy(buf[n:], m.Name)
	}
	if m.Inner != nil {
		if sz := m.Inner.SizeCodec(); sz > 0 {
			buf[n+0] = 0x12
			n += 1
			n += codec.EncodeVarint(buf[n:], uint64(sz))
			n += m.Inner.MarshalCodecInternal(buf[n:])
		}
	}
	for _, elem := range m.Children {
		if elem == nil {
			continue
		}
		buf[n+0] = 0x1a
		n += 1
		sz := elem.SizeCodec()
		n += codec.EncodeVarint(buf[n:], uint64(sz))
		n += elem.MarshalCodecInternal(buf[n:])
	}
	return n
}

func (m *Container) UnmarshalCodec(data []byte) error {
	return m.UnmarshalCodecInternal(data, string(data), 0)
}

func (m *Container) UnmarshalCodecInternal(data []byte, slab string, slabOff int) error {
	_ = slab
	_ = slabOff
	l := len(data)
	i := 0
	var seenOptional uint64
	m.Name = ""
	for _, elem := range m.Children {
		if elem != nil {
			elem.ResetCodec()
		}
	}
	m.Children = m.Children[:0]
	if m.Children == nil {
		var preCount_3 int
		pi := 0
		for pi < l {
			ptag, pn := codec.DecodeVarint(data[pi:])
			if pn < 0 {
				break
			}
			pi += pn
			pwt := ptag & 0x7
			pfn := ptag >> 3
			switch pwt {
			case 0:
				_, pn = codec.DecodeVarint(data[pi:])
				if pn < 0 {
					break
				}
				pi += pn
			case 1:
				if pi+8 > l {
					break
				}
				pi += 8
			case 2:
				pvl, pn := codec.DecodeVarint(data[pi:])
				if pn < 0 {
					break
				}
				pi += pn
				if pvl > uint64(l-pi) {
					break
				}
				switch pfn {
				case 3:
					preCount_3++
				}
				pi += int(pvl)
			case 5:
				if pi+4 > l {
					break
				}
				pi += 4
			}
		}
		if preCount_3 > 0 && m.Children == nil {
			m.Children = make([]*Inner, 0, preCount_3)
		}
	}
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("field Name (%d): %w", 1, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Name (%d): %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Name (%d): %w", 1, codec.ErrBufferTooShort)
			}
			m.Name = slab[slabOff+i : slabOff+i+int(vLen)]
			i += int(vLen)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("field Inner (%d): %w", 2, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Inner (%d): %w", 2, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Inner (%d): %w", 2, codec.ErrBufferTooShort)
			}
			if m.Inner == nil {
				m.Inner = new(Inner)
			}
			if err := m.Inner.UnmarshalCodecInternal(data[i:i+int(vLen)], slab, slabOff+i); err != nil {
				return fmt.Errorf("field Inner (%d): %w", 2, err)
			}
			seenOptional |= 1 << 2
			i += int(vLen)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("field Children (%d): %w", 3, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Children (%d): %w", 3, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Children (%d): %w", 3, codec.ErrBufferTooShort)
			}
			var elem *Inner
			if len(m.Children) < cap(m.Children) {
				m.Children = m.Children[:len(m.Children)+1]
				elem = m.Children[len(m.Children)-1]
				if elem == nil {
					elem = new(Inner)
					m.Children[len(m.Children)-1] = elem
				}
			} else {
				elem = new(Inner)
				m.Children = append(m.Children, elem)
			}
			if err := elem.UnmarshalCodecInternal(data[i:i+int(vLen)], slab, slabOff+i); err != nil {
				return fmt.Errorf("field Children (%d): %w", 3, err)
			}
			i += int(vLen)
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	if seenOptional&(1<<2) == 0 {
		m.Inner = nil
	}
	return nil
}

func (m *Container) ResetCodec() {
	if m == nil {
		return
	}
	m.Name = ""
	if m.Inner != nil {
		m.Inner.ResetCodec()
	}
	for _, elem := range m.Children {
		if elem != nil {
			elem.ResetCodec()
		}
	}
	m.Children = m.Children[:0]
}

func (m *ValueContainer) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.Name) > 0 {
		l := len(m.Name)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	if sz := (&m.Inner).SizeCodec(); sz > 0 {
		n += 1 + codec.SizeVarint(uint64(sz)) + sz
	}
	for idx := range m.Items {
		elem := &m.Items[idx]
		sz := elem.SizeCodec()
		n += 1 + codec.SizeVarint(uint64(sz)) + sz
	}
	return n
}

func (m *ValueContainer) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n := m.MarshalCodecInternal(buf)
	return buf[:n], nil
}

func (m *ValueContainer) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeCodec() {
		return 0, codec.ErrBufferTooShort
	}
	return m.MarshalCodecInternal(buf), nil
}

func (m *ValueContainer) MarshalCodecInternal(buf []byte) int {
	n := 0
	if len(m.Name) > 0 {
		buf[n+0] = 0x0a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.Name)))
		n += copy(buf[n:], m.Name)
	}
	if sz := (&m.Inner).SizeCodec(); sz > 0 {
		buf[n+0] = 0x12
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(sz))
		n += (&m.Inner).MarshalCodecInternal(buf[n:])
	}
	for idx := range m.Items {
		elem := &m.Items[idx]
		buf[n+0] = 0x1a
		n += 1
		sz := elem.SizeCodec()
		n += codec.EncodeVarint(buf[n:], uint64(sz))
		n += elem.MarshalCodecInternal(buf[n:])
	}
	return n
}

func (m *ValueContainer) UnmarshalCodec(data []byte) error {
	return m.UnmarshalCodecInternal(data, string(data), 0)
}

func (m *ValueContainer) UnmarshalCodecInternal(data []byte, slab string, slabOff int) error {
	_ = slab
	_ = slabOff
	l := len(data)
	i := 0
	m.Name = ""
	(&m.Inner).ResetCodec()
	for idx := range m.Items {
		(&m.Items[idx]).ResetCodec()
	}
	m.Items = m.Items[:0]
	if m.Items == nil {
		var preCount_3 int
		pi := 0
		for pi < l {
			ptag, pn := codec.DecodeVarint(data[pi:])
			if pn < 0 {
				break
			}
			pi += pn
			pwt := ptag & 0x7
			pfn := ptag >> 3
			switch pwt {
			case 0:
				_, pn = codec.DecodeVarint(data[pi:])
				if pn < 0 {
					break
				}
				pi += pn
			case 1:
				if pi+8 > l {
					break
				}
				pi += 8
			case 2:
				pvl, pn := codec.DecodeVarint(data[pi:])
				if pn < 0 {
					break
				}
				pi += pn
				if pvl > uint64(l-pi) {
					break
				}
				switch pfn {
				case 3:
					preCount_3++
				}
				pi += int(pvl)
			case 5:
				if pi+4 > l {
					break
				}
				pi += 4
			}
		}
		if preCount_3 > 0 && m.Items == nil {
			m.Items = make([]Inner, 0, preCount_3)
		}
	}
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("field Name (%d): %w", 1, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Name (%d): %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Name (%d): %w", 1, codec.ErrBufferTooShort)
			}
			m.Name = slab[slabOff+i : slabOff+i+int(vLen)]
			i += int(vLen)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("field Inner (%d): %w", 2, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Inner (%d): %w", 2, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Inner (%d): %w", 2, codec.ErrBufferTooShort)
			}
			if err := (&m.Inner).UnmarshalCodecInternal(data[i:i+int(vLen)], slab, slabOff+i); err != nil {
				return fmt.Errorf("field Inner (%d): %w", 2, err)
			}
			i += int(vLen)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("field Items (%d): %w", 3, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Items (%d): %w", 3, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Items (%d): %w", 3, codec.ErrBufferTooShort)
			}
			if len(m.Items) < cap(m.Items) {
				m.Items = m.Items[:len(m.Items)+1]
			} else {
				m.Items = append(m.Items, Inner{})
			}
			if err := m.Items[len(m.Items)-1].UnmarshalCodecInternal(data[i:i+int(vLen)], slab, slabOff+i); err != nil {
				return fmt.Errorf("field Items (%d): %w", 3, err)
			}
			i += int(vLen)
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *ValueContainer) ResetCodec() {
	if m == nil {
		return
	}
	m.Name = ""
	(&m.Inner).ResetCodec()
	for idx := range m.Items {
		(&m.Items[idx]).ResetCodec()
	}
	m.Items = m.Items[:0]
}

func (m *Tree) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.Label) > 0 {
		l := len(m.Label)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	for _, elem := range m.Children {
		if elem == nil {
			continue
		}
		sz := elem.SizeCodec()
		n += 1 + codec.SizeVarint(uint64(sz)) + sz
	}
	return n
}

func (m *Tree) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n := m.MarshalCodecInternal(buf)
	return buf[:n], nil
}

func (m *Tree) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeCodec() {
		return 0, codec.ErrBufferTooShort
	}
	return m.MarshalCodecInternal(buf), nil
}

func (m *Tree) MarshalCodecInternal(buf []byte) int {
	n := 0
	if len(m.Label) > 0 {
		buf[n+0] = 0x0a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.Label)))
		n += copy(buf[n:], m.Label)
	}
	for _, elem := range m.Children {
		if elem == nil {
			continue
		}
		buf[n+0] = 0x12
		n += 1
		sz := elem.SizeCodec()
		n += codec.EncodeVarint(buf[n:], uint64(sz))
		n += elem.MarshalCodecInternal(buf[n:])
	}
	return n
}

func (m *Tree) UnmarshalCodec(data []byte) error {
	return m.UnmarshalCodecInternal(data, string(data), 0)
}

func (m *Tree) UnmarshalCodecInternal(data []byte, slab string, slabOff int) error {
	_ = slab
	_ = slabOff
	l := len(data)
	i := 0
	m.Label = ""
	for _, elem := range m.Children {
		if elem != nil {
			elem.ResetCodec()
		}
	}
	m.Children = m.Children[:0]
	if m.Children == nil {
		var preCount_2 int
		pi := 0
		for pi < l {
			ptag, pn := codec.DecodeVarint(data[pi:])
			if pn < 0 {
				break
			}
			pi += pn
			pwt := ptag & 0x7
			pfn := ptag >> 3
			switch pwt {
			case 0:
				_, pn = codec.DecodeVarint(data[pi:])
				if pn < 0 {
					break
				}
				pi += pn
			case 1:
				if pi+8 > l {
					break
				}
				pi += 8
			case 2:
				pvl, pn := codec.DecodeVarint(data[pi:])
				if pn < 0 {
					break
				}
				pi += pn
				if pvl > uint64(l-pi) {
					break
				}
				switch pfn {
				case 2:
					preCount_2++
				}
				pi += int(pvl)
			case 5:
				if pi+4 > l {
					break
				}
				pi += 4
			}
		}
		if preCount_2 > 0 && m.Children == nil {
			m.Children = make([]*Tree, 0, preCount_2)
		}
	}
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("field Label (%d): %w", 1, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Label (%d): %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Label (%d): %w", 1, codec.ErrBufferTooShort)
			}
			m.Label = slab[slabOff+i : slabOff+i+int(vLen)]
			i += int(vLen)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("field Children (%d): %w", 2, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Children (%d): %w", 2, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Children (%d): %w", 2, codec.ErrBufferTooShort)
			}
			var elem *Tree
			if len(m.Children) < cap(m.Children) {
				m.Children = m.Children[:len(m.Children)+1]
				elem = m.Children[len(m.Children)-1]
				if elem == nil {
					elem = new(Tree)
					m.Children[len(m.Children)-1] = elem
				}
			} else {
				elem = new(Tree)
				m.Children = append(m.Children, elem)
			}
			if err := elem.UnmarshalCodecInternal(data[i:i+int(vLen)], slab, slabOff+i); err != nil {
				return fmt.Errorf("field Children (%d): %w", 2, err)
			}
			i += int(vLen)
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *Tree) ResetCodec() {
	if m == nil {
		return
	}
	m.Label = ""
	for _, elem := range m.Children {
		if elem != nil {
			elem.ResetCodec()
		}
	}
	m.Children = m.Children[:0]
}

func (m *MapHolder) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	for k, v := range m.Attrs {
		entrySz := 1 + codec.SizeVarint(uint64(len(k))) + len(k) + 1 + codec.SizeVarint(uint64(len(v))) + len(v)
		n += 1 + codec.SizeVarint(uint64(entrySz)) + entrySz
	}
	for k, v := range m.Counts {
		entrySz := 1 + codec.SizeVarint(uint64(len(k))) + len(k) + 1 + codec.SizeVarint(uint64(v))
		n += 1 + codec.SizeVarint(uint64(entrySz)) + entrySz
	}
	return n
}

func (m *MapHolder) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n := m.MarshalCodecInternal(buf)
	return buf[:n], nil
}

func (m *MapHolder) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeCodec() {
		return 0, codec.ErrBufferTooShort
	}
	return m.MarshalCodecInternal(buf), nil
}

func (m *MapHolder) MarshalCodecInternal(buf []byte) int {
	n := 0
	{
		keys := make([]string, 0, len(m.Attrs))
		for k := range m.Attrs {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		for _, k := range keys {
			v := m.Attrs[k]
			buf[n+0] = 0x0a
			n += 1
			entrySz := 1 + codec.SizeVarint(uint64(len(k))) + len(k) + 1 + codec.SizeVarint(uint64(len(v))) + len(v)
			n += codec.EncodeVarint(buf[n:], uint64(entrySz))
			buf[n+0] = 0x0a
			n += 1
			n += codec.EncodeVarint(buf[n:], uint64(len(k)))
			n += copy(buf[n:], k)
			buf[n+0] = 0x12
			n += 1
			n += codec.EncodeVarint(buf[n:], uint64(len(v)))
			n += copy(buf[n:], v)
		}
	}
	{
		keys := make([]string, 0, len(m.Counts))
		for k := range m.Counts {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		for _, k := range keys {
			v := m.Counts[k]
			buf[n+0] = 0x12
			n += 1
			entrySz := 1 + codec.SizeVarint(uint64(len(k))) + len(k) + 1 + codec.SizeVarint(uint64(v))
			n += codec.EncodeVarint(buf[n:], uint64(entrySz))
			buf[n+0] = 0x0a
			n += 1
			n += codec.EncodeVarint(buf[n:], uint64(len(k)))
			n += copy(buf[n:], k)
			buf[n+0] = 0x10
			n += 1
			n += codec.EncodeVarint(buf[n:], uint64(v))
		}
	}
	return n
}

func (m *MapHolder) UnmarshalCodec(data []byte) error {
	return m.UnmarshalCodecInternal(data, string(data), 0)
}

func (m *MapHolder) UnmarshalCodecInternal(data []byte, slab string, slabOff int) error {
	_ = slab
	_ = slabOff
	l := len(data)
	i := 0
	clear(m.Attrs)
	clear(m.Counts)
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("field Attrs (%d): %w", 1, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Attrs (%d): %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Attrs (%d): %w", 1, codec.ErrBufferTooShort)
			}
			if m.Attrs == nil {
				m.Attrs = make(map[string]string)
			}
			entryEnd := i + int(vLen)
			var mk string
			var mv string
			for i < entryEnd {
				etag, en := codec.DecodeVarint(data[i:entryEnd])
				if en < 0 {
					return fmt.Errorf("field Attrs (%d): %w", 1, codec.ErrInvalidVarint)
				}
				i += en
				switch etag >> 3 {
				case 1:
					sVLen, sN := codec.DecodeVarint(data[i:entryEnd])
					if sN < 0 {
						return codec.ErrInvalidVarint
					}
					i += sN
					if sVLen > uint64(entryEnd-i) {
						return codec.ErrBufferTooShort
					}
					mk = slab[slabOff+i : slabOff+i+int(sVLen)]
					i += int(sVLen)
				case 2:
					sVLen, sN := codec.DecodeVarint(data[i:entryEnd])
					if sN < 0 {
						return codec.ErrInvalidVarint
					}
					i += sN
					if sVLen > uint64(entryEnd-i) {
						return codec.ErrBufferTooShort
					}
					mv = slab[slabOff+i : slabOff+i+int(sVLen)]
					i += int(sVLen)
				default:
					sn, err := codec.SkipField(data[i:entryEnd], etag&0x7)
					if err != nil {
						return err
					}
					i += sn
				}
			}
			m.Attrs[mk] = mv
		case 2:
			if wireType != 2 {
				return fmt.Errorf("field Counts (%d): %w", 2, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Counts (%d): %w", 2, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Counts (%d): %w", 2, codec.ErrBufferTooShort)
			}
			if m.Counts == nil {
				m.Counts = make(map[string]int64)
			}
			entryEnd := i + int(vLen)
			var mk string
			var mv int64
			for i < entryEnd {
				etag, en := codec.DecodeVarint(data[i:entryEnd])
				if en < 0 {
					return fmt.Errorf("field Counts (%d): %w", 2, codec.ErrInvalidVarint)
				}
				i += en
				switch etag >> 3 {
				case 1:
					sVLen, sN := codec.DecodeVarint(data[i:entryEnd])
					if sN < 0 {
						return codec.ErrInvalidVarint
					}
					i += sN
					if sVLen > uint64(entryEnd-i) {
						return codec.ErrBufferTooShort
					}
					mk = slab[slabOff+i : slabOff+i+int(sVLen)]
					i += int(sVLen)
				case 2:
					sV, sN := codec.DecodeVarint(data[i:entryEnd])
					if sN < 0 {
						return codec.ErrInvalidVarint
					}
					i += sN
					mv = int64(sV)
				default:
					sn, err := codec.SkipField(data[i:entryEnd], etag&0x7)
					if err != nil {
						return err
					}
					i += sn
				}
			}
			m.Counts[mk] = mv
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *MapHolder) ResetCodec() {
	if m == nil {
		return
	}
	clear(m.Attrs)
	clear(m.Counts)
}

func (m *TimeHolder) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	{
		var zero time.Time
		if m.CreatedAt != zero {
			sz := codec.SizeTimestamp(m.CreatedAt)
			n += 1 + codec.SizeVarint(uint64(sz)) + sz
		}
	}
	if m.Timeout != 0 {
		sz := codec.SizeDuration(m.Timeout)
		n += 1 + codec.SizeVarint(uint64(sz)) + sz
	}
	return n
}

func (m *TimeHolder) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n := m.MarshalCodecInternal(buf)
	return buf[:n], nil
}

func (m *TimeHolder) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeCodec() {
		return 0, codec.ErrBufferTooShort
	}
	return m.MarshalCodecInternal(buf), nil
}

func (m *TimeHolder) MarshalCodecInternal(buf []byte) int {
	n := 0
	{
		var zero time.Time
		if m.CreatedAt != zero {
			buf[n+0] = 0x0a
			n += 1
			sz := codec.SizeTimestamp(m.CreatedAt)
			n += codec.EncodeVarint(buf[n:], uint64(sz))
			n += codec.EncodeTimestamp(buf[n:], m.CreatedAt)
		}
	}
	if m.Timeout != 0 {
		buf[n+0] = 0x12
		n += 1
		sz := codec.SizeDuration(m.Timeout)
		n += codec.EncodeVarint(buf[n:], uint64(sz))
		n += codec.EncodeDuration(buf[n:], m.Timeout)
	}
	return n
}

func (m *TimeHolder) UnmarshalCodec(data []byte) error {
	return m.UnmarshalCodecInternal(data, "", 0)
}

func (m *TimeHolder) UnmarshalCodecInternal(data []byte, slab string, slabOff int) error {
	_ = slab
	_ = slabOff
	l := len(data)
	i := 0
	m.CreatedAt = time.Time{}
	m.Timeout = 0
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("field CreatedAt (%d): %w", 1, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field CreatedAt (%d): %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field CreatedAt (%d): %w", 1, codec.ErrBufferTooShort)
			}
			wktV, err := codec.DecodeTimestamp(data[i : i+int(vLen)])
			if err != nil {
				return fmt.Errorf("field CreatedAt (%d): %w", 1, err)
			}
			m.CreatedAt = wktV
			i += int(vLen)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("field Timeout (%d): %w", 2, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Timeout (%d): %w", 2, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Timeout (%d): %w", 2, codec.ErrBufferTooShort)
			}
			wktV, err := codec.DecodeDuration(data[i : i+int(vLen)])
			if err != nil {
				return fmt.Errorf("field Timeout (%d): %w", 2, err)
			}
			m.Timeout = wktV
			i += int(vLen)
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *TimeHolder) ResetCodec() {
	if m == nil {
		return
	}
	m.CreatedAt = time.Time{}
	m.Timeout = 0
}

func (m *BytesPool) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.Payload) > 0 {
		l := len(m.Payload)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	return n
}

func (m *BytesPool) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n := m.MarshalCodecInternal(buf)
	return buf[:n], nil
}

func (m *BytesPool) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeCodec() {
		return 0, codec.ErrBufferTooShort
	}
	return m.MarshalCodecInternal(buf), nil
}

func (m *BytesPool) MarshalCodecInternal(buf []byte) int {
	n := 0
	if len(m.Payload) > 0 {
		buf[n+0] = 0x0a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.Payload)))
		n += copy(buf[n:], m.Payload)
	}
	return n
}

func (m *BytesPool) UnmarshalCodec(data []byte) error {
	return m.UnmarshalCodecInternal(data, "", 0)
}

func (m *BytesPool) UnmarshalCodecInternal(data []byte, slab string, slabOff int) error {
	_ = slab
	_ = slabOff
	l := len(data)
	i := 0
	m.Payload = m.Payload[:0]
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("field Payload (%d): %w", 1, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Payload (%d): %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Payload (%d): %w", 1, codec.ErrBufferTooShort)
			}
			m.Payload = append(m.Payload[:0], data[i:i+int(vLen)]...)
			i += int(vLen)
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *BytesPool) ResetCodec() {
	if m == nil {
		return
	}
	m.Payload = m.Payload[:0]
}

func (m *OneofPayload) SizeCodec() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.Label) > 0 {
		l := len(m.Label)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	}
	switch m.Kind {
	case OneofPayloadKind(10):
		l := len(m.Text)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	case OneofPayloadKind(11):
		n += 1 + codec.SizeVarint(uint64(m.Number))
	case OneofPayloadKind(12):
		sz := (&m.Nested).SizeCodec()
		n += 1 + codec.SizeVarint(uint64(sz)) + sz
	case OneofPayloadKind(13):
		l := len(m.Blob)
		n += 1 + codec.SizeVarint(uint64(l)) + l
	case OneofPayloadKind(14):
		n += 9
	}
	return n
}

func (m *OneofPayload) MarshalCodec() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeCodec()
	if size == 0 {
		return nil, nil
	}
	buf := make([]byte, size)
	n := m.MarshalCodecInternal(buf)
	return buf[:n], nil
}

func (m *OneofPayload) MarshalToCodec(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeCodec() {
		return 0, codec.ErrBufferTooShort
	}
	return m.MarshalCodecInternal(buf), nil
}

func (m *OneofPayload) MarshalCodecInternal(buf []byte) int {
	n := 0
	if len(m.Label) > 0 {
		buf[n+0] = 0x0a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.Label)))
		n += copy(buf[n:], m.Label)
	}
	switch m.Kind {
	case OneofPayloadKind(10):
		buf[n+0] = 0x52
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.Text)))
		n += copy(buf[n:], m.Text)
	case OneofPayloadKind(11):
		buf[n+0] = 0x58
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(m.Number))
	case OneofPayloadKind(12):
		buf[n+0] = 0x62
		n += 1
		sz := (&m.Nested).SizeCodec()
		n += codec.EncodeVarint(buf[n:], uint64(sz))
		n += (&m.Nested).MarshalCodecInternal(buf[n:])
	case OneofPayloadKind(13):
		buf[n+0] = 0x6a
		n += 1
		n += codec.EncodeVarint(buf[n:], uint64(len(m.Blob)))
		n += copy(buf[n:], m.Blob)
	case OneofPayloadKind(14):
		buf[n+0] = 0x71
		n += 1
		binary.LittleEndian.PutUint64(buf[n:], uint64(m.Amount))
		n += 8
	}
	return n
}

func (m *OneofPayload) UnmarshalCodec(data []byte) error {
	return m.UnmarshalCodecInternal(data, string(data), 0)
}

func (m *OneofPayload) UnmarshalCodecInternal(data []byte, slab string, slabOff int) error {
	_ = slab
	_ = slabOff
	l := len(data)
	i := 0
	m.Label = ""
	m.Text = ""
	m.Number = 0
	(&m.Nested).ResetCodec()
	m.Blob = m.Blob[:0]
	m.Amount = 0
	for i < l {
		tag, n := codec.DecodeVarint(data[i:])
		if n < 0 {
			return fmt.Errorf("offset %d: %w", i, codec.ErrInvalidTag)
		}
		i += n
		fieldNum := tag >> 3
		wireType := tag & 0x7

		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("field Label (%d): %w", 1, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Label (%d): %w", 1, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Label (%d): %w", 1, codec.ErrBufferTooShort)
			}
			m.Label = slab[slabOff+i : slabOff+i+int(vLen)]
			i += int(vLen)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("field Text (%d): %w", 10, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Text (%d): %w", 10, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Text (%d): %w", 10, codec.ErrBufferTooShort)
			}
			m.Text = slab[slabOff+i : slabOff+i+int(vLen)]
			i += int(vLen)
			m.Kind = OneofPayloadKind(10)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("field Number (%d): %w", 11, codec.ErrInvalidWireType)
			}
			v, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Number (%d): %w", 11, codec.ErrInvalidVarint)
			}
			i += n
			m.Number = int64(v)
			m.Kind = OneofPayloadKind(11)
		case 12:
			if wireType != 2 {
				return fmt.Errorf("field Nested (%d): %w", 12, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Nested (%d): %w", 12, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Nested (%d): %w", 12, codec.ErrBufferTooShort)
			}
			if err := (&m.Nested).UnmarshalCodecInternal(data[i:i+int(vLen)], slab, slabOff+i); err != nil {
				return fmt.Errorf("field Nested (%d): %w", 12, err)
			}
			i += int(vLen)
			m.Kind = OneofPayloadKind(12)
		case 13:
			if wireType != 2 {
				return fmt.Errorf("field Blob (%d): %w", 13, codec.ErrInvalidWireType)
			}
			vLen, n := codec.DecodeVarint(data[i:])
			if n < 0 {
				return fmt.Errorf("field Blob (%d): %w", 13, codec.ErrInvalidVarint)
			}
			i += n
			if uint64(l-i) < vLen {
				return fmt.Errorf("field Blob (%d): %w", 13, codec.ErrBufferTooShort)
			}
			m.Blob = append(m.Blob[:0], data[i:i+int(vLen)]...)
			i += int(vLen)
			m.Kind = OneofPayloadKind(13)
		case 14:
			if wireType != 1 {
				return fmt.Errorf("field Amount (%d): %w", 14, codec.ErrInvalidWireType)
			}
			if l-i < 8 {
				return fmt.Errorf("field Amount (%d): %w", 14, codec.ErrBufferTooShort)
			}
			m.Amount = int64(binary.LittleEndian.Uint64(data[i:]))
			i += 8
			m.Kind = OneofPayloadKind(14)
		default:
			n, err := codec.SkipField(data[i:], wireType)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

func (m *OneofPayload) ResetCodec() {
	if m == nil {
		return
	}
	m.Label = ""
	m.Text = ""
	m.Number = 0
	(&m.Nested).ResetCodec()
	m.Blob = m.Blob[:0]
	m.Amount = 0
	m.Kind = 0
}
