// Copyright 2026 Stealth Scale B.V.
// SPDX-License-Identifier: Apache-2.0

package golang

import (
	"fmt"
	"path/filepath"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"go.stealthscale.io/protoc-gen-codec/internal/core"
)

var (
	identBinaryLE         = protogen.GoIdent{GoName: "LittleEndian", GoImportPath: "encoding/binary"}
	identFmtErrorf        = protogen.GoIdent{GoName: "Errorf", GoImportPath: "fmt"}
	identErrInvalidLength = protogen.GoIdent{
		GoName:       "ErrInvalidLength",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identErrInvalidWireType = protogen.GoIdent{
		GoName:       "ErrInvalidWireType",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identSov = protogen.GoIdent{
		GoName:       "Sov",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identEncodeVarint = protogen.GoIdent{
		GoName:       "EncodeVarint",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identDecodeVarint = protogen.GoIdent{
		GoName:       "DecodeVarint",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identSkipField = protogen.GoIdent{
		GoName:       "SkipField",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identErrInvalidTag = protogen.GoIdent{
		GoName:       "ErrInvalidTag",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identErrInvalidVarint = protogen.GoIdent{
		GoName:       "ErrInvalidVarint",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identErrBufferTooShort = protogen.GoIdent{
		GoName:       "ErrBufferTooShort",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
)

func emitGoFile(
	plugin *protogen.Plugin,
	file *protogen.File,
	messages []*core.MessageInfo,
) error {
	protoName := file.Proto.GetName()
	base := strings.TrimSuffix(filepath.Base(protoName), ".proto")
	dir := filepath.Dir(protoName)
	filename := filepath.Join(dir, base+".codec.go")

	g := plugin.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-codec-go. DO NOT EDIT.")
	g.P("// source: ", protoName)
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, info := range messages {
		generateSizeCodec(g, info)
		g.P()
		generateMarshalCodec(g, info)
		g.P()
		generateMarshalToCodec(g, info)
		g.P()
		generateUnmarshalCodec(g, info)
		g.P()
		generateResetCodec(g, info)
		g.P()
	}

	return nil
}

func emitTag(g *protogen.GeneratedFile, fieldNum int32, wk core.WireKind, bufVar string, offsetVar string) {
	tb := core.TagBytes(fieldNum, wk)
	for i, b := range tb {
		g.P(bufVar, "[", offsetVar, "+", i, "] = ", fmt.Sprintf("0x%02x", b))
	}
	g.P(offsetVar, " += ", len(tb))
}
