// Copyright 2026 Stealth Scale B.V.
// SPDX-License-Identifier: Apache-2.0

package golang

import (
	"fmt"
	"path/filepath"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"go.stealthscale.io/protoc-gen-codec/internal/core"
)

var (
	identBinaryLE         = protogen.GoIdent{GoName: "LittleEndian", GoImportPath: "encoding/binary"}
	identFmtErrorf        = protogen.GoIdent{GoName: "Errorf", GoImportPath: "fmt"}
	identErrInvalidLength = protogen.GoIdent{
		GoName:       "ErrInvalidLength",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identErrInvalidWireType = protogen.GoIdent{
		GoName:       "ErrInvalidWireType",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identSov = protogen.GoIdent{
		GoName:       "Sov",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identEncodeVarint = protogen.GoIdent{
		GoName:       "EncodeVarint",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identDecodeVarint = protogen.GoIdent{
		GoName:       "DecodeVarint",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identSkipField = protogen.GoIdent{
		GoName:       "SkipField",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identErrInvalidTag = protogen.GoIdent{
		GoName:       "ErrInvalidTag",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identErrInvalidVarint = protogen.GoIdent{
		GoName:       "ErrInvalidVarint",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identErrBufferTooShort = protogen.GoIdent{
		GoName:       "ErrBufferTooShort",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identZigzagEncode32 = protogen.GoIdent{
		GoName:       "ZigzagEncode32",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identZigzagEncode64 = protogen.GoIdent{
		GoName:       "ZigzagEncode64",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identZigzagDecode32 = protogen.GoIdent{
		GoName:       "ZigzagDecode32",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identZigzagDecode64 = protogen.GoIdent{
		GoName:       "ZigzagDecode64",
		GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec",
	}
	identTimeTime        = protogen.GoIdent{GoName: "Time", GoImportPath: "time"}
	identSlicesSorted    = protogen.GoIdent{GoName: "Sorted", GoImportPath: "slices"}
	identMapsKeys        = protogen.GoIdent{GoName: "Keys", GoImportPath: "maps"}
	identSizeTimestamp   = protogen.GoIdent{GoName: "SizeTimestamp", GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec"}
	identSizeDuration    = protogen.GoIdent{GoName: "SizeDuration", GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec"}
	identEncodeTimestamp = protogen.GoIdent{GoName: "EncodeTimestamp", GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec"}
	identEncodeDuration  = protogen.GoIdent{GoName: "EncodeDuration", GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec"}
	identDecodeTimestamp = protogen.GoIdent{GoName: "DecodeTimestamp", GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec"}
	identDecodeDuration  = protogen.GoIdent{GoName: "DecodeDuration", GoImportPath: "go.stealthscale.io/protoc-gen-codec/lang/go/codec"}
)

func emitGoFile(
	plugin *protogen.Plugin,
	file *protogen.File,
	fileMap map[string]*protogen.File,
	messages []*core.MessageInfo,
) error {
	protoName := file.Proto.GetName()
	base := strings.TrimSuffix(filepath.Base(protoName), ".proto")
	dir := filepath.Dir(protoName)
	filename := filepath.Join(dir, base+".codec.go")

	g := plugin.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-codec-go. DO NOT EDIT.")
	g.P("// source: ", protoName)
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, info := range messages {
		generateSizeCodec(g, fileMap, info)
		g.P()
		generateMarshalCodec(g, info)
		g.P()
		generateMarshalToCodec(g, fileMap, info)
		g.P()
		generateUnmarshalCodec(g, fileMap, info)
		g.P()
		generateResetCodec(g, fileMap, info)
		g.P()
	}

	return nil
}

func emitTag(g *protogen.GeneratedFile, fieldNum int32, wk core.WireKind) {
	tb := core.TagBytes(fieldNum, wk)
	for i, b := range tb {
		g.P("buf[n+", i, "] = ", fmt.Sprintf("0x%02x", b))
	}
	g.P("n += ", len(tb))
}
